### PR TITLE
Make XorshiftEngine template work with any UIntType

### PR DESCRIPTION
**Pull request by n8sh**
Make XorshiftEngine template work with any UIntType while maintaining full backward compatibility. Unittests in `mir.random.algorithm` verified that the results did not change.

### CODE REVIEW

**Comment by 9il** [comment]
Unittests for ulong are required.

BTW, what the motivation?

**Comment by n8sh** [comment]
>BTW, what the motivation?

Although I no longer have a personal need for it, in the past I wanted to use `XorshiftEngine` as an internal building block for other algorithms. I was reminded of this again recently because it's something that's still broken in Phobos. `std.random.XorshiftEngine` https://issues.dlang.org/show_bug.cgi?id=18327 (*std.random.XorshiftEngine is parameterized by UIntType but only works with uint*).

**Comment by 9il** [comment]
Because of internal constants and shifts probably xorshift must be used only with 32 bit uints.

**Comment by 9il** [comment]
This is why I removed other types

**Comment by n8sh** [comment]
>Unittests for ulong are required.

There are a number of improvements I want to make to this PR. Should I close it for now then re-open it when it is ready?

>BTW, what the motivation?

Now I remember the other half of the motivation: being able to specify the _directions_ of shifts.

**Comment by 9il** [comment]
The pr can be open, no worries

**Comment by n8sh** [comment]
>Unittests for ulong are required.

@9il Now fully tested and ready for review / merge. My ultimate plan is to merge parts of this back upstream to Phobos to fix [Issue 18327 - _std.random.XorshiftEngine is parameterized by UIntType but only works with uint_](https://issues.dlang.org/show_bug.cgi?id=18327).

**Pull request merged**
