### PR TITLE
Upgrade pyd to v0.13.0

### PR DESCRIPTION
**Pull request by Geod24**
Use a newer version which does not depend on class deallocator.

### CODE REVIEW

**Comment by Geod24** [comment]
Looks like the tests SEGV now :/

**Comment by Geod24** [comment]
Hum it looks like master have been broken for a while. @9il can you take a look ? This blocks a DMD PR.

**Comment by 9il** [comment]
No idea why Travis is failing

**Comment by Geod24** [comment]
Unfortunately that won't be enough to unblock the DMD PR.
A new tagged version is needed, which by itself will create other problems if the CI is failing.

So here are the two options I see:
1) Temporarily disable mir-random in `dlang/ci`
2) Fix the CI and make a new point release

The latter would be preferred, but if you don't have the time, I can go with the former. Just let me know what works for you. The PR to DMD is not time-critical, since we're still far away from the next minor release, so there's a bit of time to address the issue.

**Comment by 9il** [comment]
tagged with `v2.2.10`, the previous releases failed in the CI anyway

**Comment by Geod24** [comment]
Thanks!

**Pull request merged**
