### PR TITLE
Use GDC builtins & mir.bitop

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Comment by 9il** [comment]
It is lagacy code. Currently mir.bitop should be used instead  https://github.com/libmir/mir-core/blob/master/source/mir/bitop.d#L350

**Comment by n8sh** [comment]
Replaced legacy code with `mir.bitop`.

**Comment by 9il** [comment]
@n8sh  i added one commit

**Comment by n8sh** [comment]
Good to go?

**Comment by 9il** [comment]
merged

**Pull request merged**
